/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcfunc.h"

bool_t
xdr_paper_data (XDR *xdrs, paper_data *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->paper_data_val, (u_int *) &objp->paper_data_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_int_in (XDR *xdrs, int_in *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_int_out (XDR *xdrs, int_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_list_in (XDR *xdrs, list_in *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_paper_information (XDR *xdrs, paper_information *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->author, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->title, ~0))
		 return FALSE;
	 if (!xdr_paper_data (xdrs, &objp->paper))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_paper_list_out (XDR *xdrs, paper_list_out *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (paper_list_out), (xdrproc_t) xdr_paper_list_out))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->prev, sizeof (paper_list_out), (xdrproc_t) xdr_paper_list_out))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->paper_info, sizeof (paper_information), (xdrproc_t) xdr_paper_information))
		 return FALSE;
	return TRUE;
}
