/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCFUNC_H_RPCGEN
#define _RPCFUNC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int paper_data_len;
	char *paper_data_val;
} paper_data;

typedef int int_in;

typedef int int_out;

typedef int list_in;

struct paper_information {
	char *author;
	char *title;
	paper_data paper;
};
typedef struct paper_information paper_information;

struct paper_list_out {
	struct paper_list_out *next;
	struct paper_list_out *prev;
	int id;
	struct paper_information *paper_info;
};
typedef struct paper_list_out paper_list_out;

#define RPC_FUNCTIONS 0x00000042
#define RPC_FUNC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define REMOVE_PAPER 1
extern  int_out * remove_paper_1(int_in *, CLIENT *);
extern  int_out * remove_paper_1_svc(int_in *, struct svc_req *);
#define FETCH_PAPER 2
extern  paper_data * fetch_paper_1(int_in *, CLIENT *);
extern  paper_data * fetch_paper_1_svc(int_in *, struct svc_req *);
#define INFO_PAPER 3
extern  paper_information * info_paper_1(int_in *, CLIENT *);
extern  paper_information * info_paper_1_svc(int_in *, struct svc_req *);
#define LIST_PAPER 4
extern  paper_list_out * list_paper_1(list_in *, CLIENT *);
extern  paper_list_out * list_paper_1_svc(list_in *, struct svc_req *);
#define ADD_PAPER 5
extern  int_out * add_paper_1(paper_information *, CLIENT *);
extern  int_out * add_paper_1_svc(paper_information *, struct svc_req *);
extern int rpc_functions_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define REMOVE_PAPER 1
extern  int_out * remove_paper_1();
extern  int_out * remove_paper_1_svc();
#define FETCH_PAPER 2
extern  paper_data * fetch_paper_1();
extern  paper_data * fetch_paper_1_svc();
#define INFO_PAPER 3
extern  paper_information * info_paper_1();
extern  paper_information * info_paper_1_svc();
#define LIST_PAPER 4
extern  paper_list_out * list_paper_1();
extern  paper_list_out * list_paper_1_svc();
#define ADD_PAPER 5
extern  int_out * add_paper_1();
extern  int_out * add_paper_1_svc();
extern int rpc_functions_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_paper_data (XDR *, paper_data*);
extern  bool_t xdr_int_in (XDR *, int_in*);
extern  bool_t xdr_int_out (XDR *, int_out*);
extern  bool_t xdr_list_in (XDR *, list_in*);
extern  bool_t xdr_paper_information (XDR *, paper_information*);
extern  bool_t xdr_paper_list_out (XDR *, paper_list_out*);

#else /* K&R C */
extern bool_t xdr_paper_data ();
extern bool_t xdr_int_in ();
extern bool_t xdr_int_out ();
extern bool_t xdr_list_in ();
extern bool_t xdr_paper_information ();
extern bool_t xdr_paper_list_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCFUNC_H_RPCGEN */
